"""add rssi proper

Revision ID: 01d498e6d20c
Revises: 16d8a6861b95
Create Date: 2025-02-26 22:09:47.857866

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d498e6d20c'
down_revision = '16d8a6861b95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('rssi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensormetric', 'rssi')
    # ### end Alembic commands ###
