"""fix field names

Revision ID: 16d8a6861b95
Revises: c901097f28e0
Create Date: 2025-02-17 19:39:28.715246

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d8a6861b95'
down_revision = 'c901097f28e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('device_id', sa.Integer(), nullable=False))
    op.drop_column('sensormetric', 'sensor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sensormetric', 'device_id')
    # ### end Alembic commands ###
