"""fix datetime fields

Revision ID: 320828741745
Revises: 3b7bbd1ea3aa
Create Date: 2025-03-20 23:00:53.501280

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320828741745'
down_revision = '3b7bbd1ea3aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
