"""new data tables for visualization

Revision ID: 3b3714587fa4
Revises: cae523326767
Create Date: 2025-03-20 21:34:29.263220

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b3714587fa4'
down_revision = 'cae523326767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('appeui', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deveui', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('appkey', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ground_cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_above_ground', sa.Integer(), nullable=True),
    sa.Column('shading', sa.Integer(), nullable=True),
    sa.Column('close_to_a_tree', sa.Boolean(), nullable=True),
    sa.Column('close_to_water', sa.Boolean(), nullable=True),
    sa.Column('orientation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('distance_to_next_building_cm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('hardwarerevision',
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specification_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specification_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specification_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('hardware_id')
    )
    op.create_table('softwareversion',
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('git_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('software_id')
    )
    op.add_column('sensormetric', sa.Column('device_id', sa.Integer(), nullable=True))
    op.alter_column('sensormetric', 'timestamp_device',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sensormetric', 'timestamp_server',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sensormetric', 'temperature',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensormetric', 'humidity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('sensormetric', 'sensor_id')
    op.drop_column('sensormetric', 'rssi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('rssi', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensormetric', sa.Column('sensor_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('sensormetric', 'humidity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensormetric', 'temperature',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sensormetric', 'timestamp_server',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sensormetric', 'timestamp_device',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sensormetric', 'device_id')
    op.drop_table('softwareversion')
    op.drop_table('hardwarerevision')
    op.drop_table('device')
    # ### end Alembic commands ###
