"""add sensor message model and new metric fields

Revision ID: 49d68a8a911d
Revises: a475467f8545
Create Date: 2025-10-22 18:57:17.318424

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d68a8a911d'
down_revision = 'a475467f8545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensormessage',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'gateway_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('rssi', sa.Float(), nullable=True),
                    sa.Column('snr', sa.Float(), nullable=True),
                    sa.Column('channel_rssi', sa.Float(), nullable=True),
                    sa.Column('lora_bandwidth', sa.Integer(), nullable=True),
                    sa.Column('lora_spreading_factor',
                              sa.Integer(), nullable=True),
                    sa.Column('lora_coding_rate',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('device_id', sa.Integer(), nullable=True),
                    sa.Column('sensor_metric_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['device_id'], ['device.device_id'], ),
                    sa.ForeignKeyConstraint(['sensor_metric_id'], [
                                            'sensormetric.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sensormessagetaglink',
                    sa.Column('sensor_message_id',
                              sa.Integer(), nullable=False),
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['sensor_message_id'], [
                                            'sensormessage.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
                    sa.PrimaryKeyConstraint('sensor_message_id', 'tag_id')
                    )
    op.add_column('sensormetric', sa.Column(
        'confirmed', sa.Boolean(), nullable=True))
    op.add_column('sensormetric', sa.Column(
        'consumed_airtime', sa.Float(), nullable=True))
    op.add_column('sensormetric', sa.Column(
        'f_cnt', sa.Integer(), nullable=True))
    op.add_column('sensormetric', sa.Column(
        'frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensormetric', 'frequency')
    op.drop_column('sensormetric', 'f_cnt')
    op.drop_column('sensormetric', 'consumed_airtime')
    op.drop_column('sensormetric', 'confirmed')
    op.drop_table('sensormessagetaglink')
    op.drop_table('sensormessage')
    # ### end Alembic commands ###
