"""add surrounding shading attribute

Revision ID: 49e4ba4feec1
Revises: 3cc0f020d70e
Create Date: 2025-07-07 19:39:59.301489

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e4ba4feec1'
down_revision = '3cc0f020d70e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('shading_of_surrounding_area', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'shading_of_surrounding_area')
    # ### end Alembic commands ###
