"""add_battery_voltage

Revision ID: 4c7ba4fbba32
Revises: f979d5c3305a
Create Date: 2025-07-26 13:14:00.719769

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7ba4fbba32'
down_revision = 'f979d5c3305a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
