"""add optional comment fields

Revision ID: a475467f8545
Revises: cb685d201e88
Create Date: 2025-10-12 09:09:58.429384

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a475467f8545'
down_revision = 'cb685d201e88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardwarerevision', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('softwareversion', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tag', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'comment')
    op.drop_column('softwareversion', 'comment')
    op.drop_column('hardwarerevision', 'comment')
    # ### end Alembic commands ###
