"""add_device_comment

Revision ID: b7026f391e53
Revises: ca6e4c1fcfc8
Create Date: 2025-10-11 14:21:16.294921

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7026f391e53'
down_revision = 'ca6e4c1fcfc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column(
        'comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'comment')
    # ### end Alembic commands ###
