"""init

Revision ID: c901097f28e0
Revises: 
Create Date: 2025-02-17 19:35:51.461253

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c901097f28e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensormetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_device', sa.Integer(), nullable=False),
    sa.Column('timestamp_server', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensormetric')
    # ### end Alembic commands ###
