"""add_battery_voltage

Revision ID: ca6e4c1fcfc8
Revises: 4c7ba4fbba32
Create Date: 2025-07-26 14:19:22.393067

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6e4c1fcfc8'
down_revision = '4c7ba4fbba32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('battery_voltage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensormetric', 'battery_voltage')
    # ### end Alembic commands ###
