"""rename to sensor id

Revision ID: cae523326767
Revises: e257ca7f7e9d
Create Date: 2025-03-09 18:44:12.139846

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae523326767'
down_revision = 'e257ca7f7e9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('sensor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('sensormetric', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sensormetric', 'sensor_id')
    # ### end Alembic commands ###
