"""change device id to str

Revision ID: e257ca7f7e9d
Revises: 01d498e6d20c
Create Date: 2025-03-09 17:59:58.755529

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e257ca7f7e9d'
down_revision = '01d498e6d20c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
