"""device to int

Revision ID: ef984db53161
Revises: d69872796bc7
Create Date: 2025-03-20 23:21:04.443939

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef984db53161'
down_revision = 'd69872796bc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_software_id_fkey', 'device', type_='foreignkey')
    op.drop_constraint('device_hardware_id_fkey', 'device', type_='foreignkey')
    op.drop_constraint('sensormetric_device_id_fkey', 'sensormetric', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sensormetric_device_id_fkey', 'sensormetric', 'device', ['device_id'], ['device_id'])
    op.create_foreign_key('device_hardware_id_fkey', 'device', 'hardwarerevision', ['hardware_id'], ['hardware_id'])
    op.create_foreign_key('device_software_id_fkey', 'device', 'softwareversion', ['software_id'], ['software_id'])
    # ### end Alembic commands ###
