"""add air pressure

Revision ID: f979d5c3305a
Revises: 1f1c7c945045
Create Date: 2025-07-24 07:46:44.567980

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f979d5c3305a'
down_revision = '1f1c7c945045'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensormetric', sa.Column('air_pressure', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensormetric', 'air_pressure')
    # ### end Alembic commands ###
