name: stage deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, quantum_server]
    concurrency:
      group: run_stage
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Write .env file
        run: echo "${{ secrets.QUANTUM_ENV_STAGE }}" > .env

      - name: Build and Run Docker image
        run: |
          docker compose -p quantum_stage -f docker-compose.yml up -d --build

      - name: Run database migrations
        run: |
          docker exec quantum_web_stage alembic upgrade head

      - name: Run integration tests
        run: |
          python3 -m pytest test/integration
      
      - name: Run prod tests
        run: |
          python3 -m pytest test/integration