name: prod deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: quantum_server
    concurrency:
      group: run_prod
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      - name: Write .env file
        run: echo "${{ secrets.QUANTUM_ENV_PROD }}" > .env

      - name: Check environment variables
        run: python3 devops/check_env_vars.py
        
      - name: Build and Run Docker image
        run: |
          docker compose -p quantum_prod -f docker-compose.yml pull
          docker compose -p quantum_prod -f docker-compose.yml down
          docker compose -p quantum_prod -f docker-compose.yml up -d --build

      - name: Run database migrations
        run: |
          docker exec quantum_web_prod alembic upgrade head

      - name: Run prod tests
        run: |
          python3 -m pytest test/prod